### ISSUE TITLE
Setup staging and github actions for Louisville

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/louisville-hyku#163]
# Summary

LV now has a maintenance contract.  They do not need monitoring, but in order to better understand where issues may be arising we want to have a staging instance to test code on. The previous instance was broken, and github is not set up to deploy to it. 

# Acceptance Criteria

- [x] github can deploy to staging
- [x] staging instance is back up and working. 

New staging url: https://louisville-hyku-staging.notch8.cloud/

**Comment by crisr15** [comment]
Set up staging again.

**Comment by bkiahstroud** [comment]
PR: https://github.com/scientist-softserv/louisville-hyku/pull/164

**Comment by bkiahstroud** [comment]
PR: https://github.com/scientist-softserv/louisville-hyku/pull/165
