### ISSUE TITLE
Failing PDF uploads

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/louisville-hyku#167]
# Summary
One example of a PDF upload failing to include all the pages in the viewer is https://hyku-docker-dev.library.louisville.edu/concern/texts/senior_bulletin_19751976?locale=en (also note the slowness of the files in the viewer!). Pages 12 and 18 show up as blank icons in my admin view, and don't materialize at all in the viewer. I think this collection was reimported to try to correct some of the errors in the initial import; pretty sure that initially certain pages didn't even appear in the admin view.

# Accepted Criteria
- [x] When a PDF is uploaded, all of the pages and their content show in the viewer

# Testing Instructions

# Notes

**Comment by rachelihoward** [comment]
Bug fixes took care of this problem.
