### ISSUE TITLE
Uploaded collection had issues generating JPG

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/louisville-hyku#168]
# Summary
Uploaded a collection of 10 PDFs yesterday, and in addition to other issues, one of them had an issue generating the JPG for the first page (see error in Sidekiq).

![Image](https://user-images.githubusercontent.com/84697174/214899410-03ce270e-4892-45fa-a8f2-8438b071f24f.jpg)

# Accepted Criteria
- [x] When PDFs are imported, JPGs generate for all of the pages

# Testing Instructions

# Notes

**Comment by rachelihoward** [comment]
Bug fixes seem to have taken care of this issue.
