### ISSUE TITLE
works with a filename that includes the letter “s” before the filetype are skipped

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/louisville-hyku#172]
# Summary

During bulkrax ingest some children have alphanumeric filenames, and I’ve noticed that when a filename includes the letter “s” before the filetype it is skipped – is there something in the code that treats an “s” before a filetype as a stop word? See, for example, https://hyku-docker-dev.library.louisville.edu/concern/images/ulua_2006_003_008_299/ - it skips from ulua_2006_003_008_299r to ulua_2006_003_008_299t

# Acceptance Criteria

- [x] I can upload a work with children that have alphanumeric filenames and it attaches all the children.  

# Testing Instructions
 - File is in client folder under shared resources. 

# Notes

When looking at the file mentioned above I noticed that the file ulua_2006_003_008_299f was also missing.  
Confirmed in meeting that 's' is the repeated problem.  Do not worry about f missing currently on this one item.

**Comment by alishaevn** [comment]
<details>
<summary> stephs.jpg </summary>

![Image](https://user-images.githubusercontent.com/29032869/228576370-9cfbb3a0-3823-4ba5-8faa-32762e98d692.png)
</details>

<details>
<summary> klays.jpg </summary>

![Image](https://user-images.githubusercontent.com/29032869/228577000-fb9e0f7d-b629-4cd7-9566-b8e331b801fc.png)
</details>

<details>
<summary> drays.jpg </summary>

![Image](https://user-images.githubusercontent.com/29032869/228577321-3654702b-710f-4bb9-9870-660e408c3ab5.png)
</details>

**Comment by alishaevn** [comment]
[celtics.csv](https://github.com/scientist-softserv/louisville-hyku/files/11103049/celtics.csv)

the test in my comment above was done by uploading a csv. I then imported the celtics.csv file above using the server path upload method. it also uploaded fine.

I am unable to reproduce this error locally so far.

![Image](https://user-images.githubusercontent.com/29032869/228603209-de63ed3c-4233-4355-a944-63d9ddb0eefc.png)

**Comment by alishaevn** [comment]
@rachelihoward can you upload the`ULUA 2006_003_008_064` "a-s" files that are related to the "owen_compoundObjects_sample.csv" file, into [this folder](https://drive.google.com/drive/folders/1q9d-C4Y34EqPB-HbywmCgIWCqFT8qTsr) of the google drive?

since I'm unable to reproduce the error locally with my own files, I'd like to see if I can reproduce the error with files you all are using.

also, can you please take a look at my question to you and/or randy in the [samvera channel](https://samvera.slack.com/archives/C034S4UF53L/p1680042780083409)?

**Comment by alishaevn** [comment]
by happenstance, I _believe_ I'm come across the actual issue. I think the problem is related to when the `source_identifier` ends in "s", not the file.

still troubleshooting.

**Comment by rachelihoward** [comment]
Alisha,

I just requested permissions for that drive.

Randy is working on setting up a user account – what were you planning to use it for?

Rachel

**Comment by rachelihoward** [comment]
That's great news, Alisha!

**Comment by rachelihoward** [comment]
Sending files to the Google Drive now - it says it will take over an hour. Also, please remove ULUA 2006_003_008_230t from the csv. I don't know why I eliminated the parent and the rest of the children for that one from the sample set but it's not useful to just have that one child record. I think there are plenty of other examples without it!

**Comment by alishaevn** [comment]
[kevons.zip](https://github.com/scientist-softserv/louisville-hyku/files/11105704/kevons.zip)

<details>
<summary>importer 7</summary>

![Image](https://user-images.githubusercontent.com/29032869/228674554-188a98df-e9be-4083-9aa5-9fae5400a292.png)
</details>

``` bash
i = Bulkrax::Importers.find(7)
e = i.entries.last

begin
  e.factory.run
rescue
  e
end
```

running the above in my rails console has led me to [Hyrax::Actors::TransactionalRequest.create](https://github.com/samvera/hyrax/blob/v2.9.6/app/actors/hyrax/actors/transactional_request.rb#L12-L14). this method returns `false`. according to the comment above the method, returning true means that the `create` was successful. so I think this is where the problem lies. not sure _why_ though.

**Comment by alishaevn** [comment]
according to the console, `next_actor` inside transactional request should be `[Hyrax::Actors::OptimisticLockValidator](https://github.com/samvera/hyrax/blob/v2.9.6/app/actors/hyrax/actors/optimistic_lock_validator.rb). that class doesn't have a `create` method in hyrax `2.9.6` though. 🤔

**Comment by alishaevn** [comment]
``` bash
[16] pry(#<Hyrax::Actors::TextActor>)> env.curation_concern.valid?
=> false
[17] pry(#<Hyrax::Actors::TextActor>)> env.curation_concern.errors.messages
=> {:identifier=>["must be unique"]}
[18] pry(#<Hyrax::Actors::TextActor>)> step

From: /usr/local/bundle/gems/active-fedora-12.2.3/lib/active_fedora/associations/builder/orders.rb:44 ActiveFedora::Associations::Builder::Orders::FixFirstLast#save:

    43: def save(*args)
 => 44:   super.tap do |result|
    45:     apply_first_and_last if result
    46:   end
    47: end

[18] pry(#<Text>)> step

From: /usr/local/bundle/gems/active-fedora-12.2.3/lib/active_fedora/validations.rb:50 ActiveFedora::Validations#save:

    49: def save(options = {})
 => 50:   perform_validations(options) ? super : false
    51: end

[18] pry(#<Text>)> perform_validations(options)
=> false
```

**Comment by alishaevn** [comment]
@bkiahstroud suggested I see if this same error happens when creating a work manually; it does. this confirms that the problem is somewhere in the hyrax pathway. 

I created a work with a `title` and `item number` of "single". no file or any other metadata. I then tried creating a second work with a `title` and `item number` of "single**s**". it failed with the error below. I then created a third work with a `title` and `item number` of "doubles". that succeeded. so having an "s" at the end of the identifier alone isn't a problem. it's when that identifier without an "s" is the same as another work that already exists.


<details>
<summary>single</summary>

``` bash
#<Text id: "3e05bbd2-af85-4286-9bc3-570183ce3875", head: [], tail: [], depositor: "admin@example.com", title: ["single"], date_uploaded: "2023-03-30 22:14:40", date_modified: "2023-03-30 22:14:40", state: #<ActiveTriples::Resource:0x6ca48 ID:<http://fedora.info/definitions/1/0/access/ObjState#active>>, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksum: nil, owner: nil, is_child: nil, slug: "single", alternative_title: [], collection_information: [], contributor_role: [], creator_role: [], date_digital: nil, digitization_specification: nil, format: nil, location: [], media_type: [], mesh: [], ordering_information: nil, people_represented: [], resource_query: [], issue: nil, searchable_text: nil, table_of_contents: nil, volume: nil, label: nil, relative_path: nil, import_url: nil, resource_type: [], creator: [], contributor: [], description: [], keyword: [], license: [], rights_statement: [], publisher: [], date_created: [], subject: [], language: [], identifier: ["single"], based_near: [], related_url: [], bibliographic_citation: [], source: [], access_control_id: "1f472c1b-6603-46ec-8606-8e9a4e3a542b", representative_id: nil, thumbnail_id: nil, rendering_ids: [], admin_set_id: "admin_set/default", embargo_id: nil, lease_id: nil>
```

![Image](https://user-images.githubusercontent.com/29032869/228978261-1b7be68e-2780-4164-ba2c-1165774f9531.png)


</details>

<details>
<summary>singles</summary>

![Image](https://user-images.githubusercontent.com/29032869/228976792-b9031ec4-e205-468c-b50b-0d87fa176cc7.png)
</details>

<details>
<summary>doubles</summary>

``` bash
#<Text id: "3f24fc62-d48c-415b-9930-a855e2cb32f3", head: [], tail: [], depositor: "admin@example.com", title: ["doubles"], date_uploaded: "2023-03-30 22:24:01", date_modified: "2023-03-30 22:24:02", state: #<ActiveTriples::Resource:0x6ca5c ID:<http://fedora.info/definitions/1/0/access/ObjState#active>>, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksum: nil, owner: nil, is_child: nil, slug: "doubles", alternative_title: [], collection_information: [], contributor_role: [], creator_role: [], date_digital: nil, digitization_specification: nil, format: nil, location: [], media_type: [], mesh: [], ordering_information: nil, people_represented: [], resource_query: [], issue: nil, searchable_text: nil, table_of_contents: nil, volume: nil, label: nil, relative_path: nil, import_url: nil, resource_type: [], creator: [], contributor: [], description: [], keyword: [], license: [], rights_statement: [], publisher: [], date_created: [], subject: [], language: [], identifier: ["doubles"], based_near: [], related_url: [], bibliographic_citation: [], source: [], access_control_id: "ba09fc01-0d98-4177-b4ec-2157dcd9cbe3", representative_id: nil, thumbnail_id: nil, rendering_ids: [], admin_set_id: "admin_set/default", embargo_id: nil, lease_id: nil>
```

![Image](https://user-images.githubusercontent.com/29032869/228978237-9dd65b9a-c9d3-4c03-937d-1ef9bc941d00.png)


</details>

this already appeared to be true because `identifier` is a property in [Hyrax::BasicMetadata](https://github.com/samvera/hyrax/blob/main/app/models/concerns/hyrax/basic_metadata.rb#L35). it's created by [rdf-vocab](https://github.com/ruby-rdf/rdf-vocab/blob/a6d073b6ac647645b7d9f5a6bd7f8688bb7378f6/lib/rdf/vocab/dc.rb#L380-L388), but I don't see any validation rules yet.

[dublin core specs](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/identifier/)

**Comment by alishaevn** [comment]
I went back through the actor stack and discovered that the identifier gets set somewhere in [Hyrax::Actors::BaseActors#create](https://github.com/samvera/hyrax/blob/v2.9.6/app/actors/hyrax/actors/base_actor.rb#L18-L22). trying to save the new `curation_concern`, fails.

<details>
<summary>related console logs</summary>

``` bash
# entering the method
From: /usr/local/bundle/gems/hyrax-2.9.6/app/actors/hyrax/actors/base_actor.rb:19 Hyrax::Actors::BaseActor#create:

    18: def create(env)
 => 19:   apply_creation_data_to_curation_concern(env)
    20:   apply_save_data_to_curation_concern(env)
    21:   save(env) && next_actor.create(env) && run_callbacks(:after_create_concern, env)
    22: end

[14] pry(#<Hyrax::Actors::TextActor>)> env.curation_concern.identifier
=> []


# exiting the method
From: /usr/local/bundle/gems/hyrax-2.9.6/app/actors/hyrax/actors/base_actor.rb:68 Hyrax::Actors::BaseActor#save:

    67: def save(env)
 => 68:   env.curation_concern.save
    69: end

[15] pry(#<Hyrax::Actors::TextActor>)> env.curation_concern.identifier
=> ["Kevons"]
[16] pry(#<Hyrax::Actors::TextActor>)> env.curation_concern.save
=> false
```
</details>

**Comment by alishaevn** [comment]
further down the rabbit hole...the problem more closely lies somewhere in the [ActiveFedora::Validations#run_validations!](https://github.com/samvera/active_fedora/blob/main/lib/active_fedora/validations.rb#L99-L101) method calls.

when I entered [ActiveFEDORA::Validations#valid?](https://github.com/samvera/active_fedora/blob/main/lib/active_fedora/validations.rb#L67-L71), it called `super` and led me to [ActiveMODEL::Validations#valid?](https://github.com/rails/rails/blob/main/activemodel/lib/active_model/validations.rb#L363-L369). once there, the `errors` object had empty hashes for the `details` and `messages` values. I stepped into the next methods, which was a series of callbacks kicked off by `run_validations!`(in ActiveFEDORA), and still didn't see anywhere where an error was set. however, as ActiveMODEL::Validations#valid? wrapped up and brought me back to ActiveFEDORA::Validations#valid?, `errors.details` and `errors.messages` had data.

<details>
<summary>errors</summary>

``` bash
From: /usr/local/bundle/gems/activemodel-5.2.7.1/lib/active_model/validations.rb:338 ActiveModel::Validations#valid?:
    336: def valid?(context = nil)
    337:   current_context, self.validation_context = validation_context, context
 => 338:   errors.clear
    339:   run_validations!
    340: ensure
    341:   self.validation_context = current_context
    342: end

[5] pry(#<Text>)> current_context
=> nil
[6] pry(#<Text>)> self.validation_context
=> :create
[7] pry(#<Text>)> errors
=> #<ActiveModel::Errors:0x000055ce9d47e750
 @base=
  #<Text id: nil, head: [], tail: [], depositor: "admin@example.com", title: ["Kevon Looney"], date_uploaded: "2023-03-31 17:06:27", date_modified: "2023-03-31 17:06:27", state: nil, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksu
m: nil, owner: nil, is_child: nil, slug: nil, alternative_title: [], collection_information: [], contributor_role: ["publisher"], creator_role: [], date_digital: nil, digitization_specification: "digitization_specification", format: "", l
ocation: [], media_type: ["Text"], mesh: [], ordering_information: nil, people_represented: [], resource_query: [], issue: "No. 2.", searchable_text: "Looney always holds us down!", table_of_contents: nil, volume: "Vol 2.", label: nil, re
lative_path: nil, import_url: nil, resource_type: ["Newspapers"], creator: [], contributor: ["Adam Silver"], description: ["Dub nation"], keyword: [], license: [], rights_statement: [], publisher: ["repository"], date_created: ["2/9/2022"
], subject: ["This is the subject"], language: [], identifier: ["Kevons"], based_near: [], related_url: [], bibliographic_citation: [], source: ["The source"], access_control_id: nil, representative_id: nil, thumbnail_id: nil, rendering_i
ds: [], admin_set_id: "admin_set/default", embargo_id: nil, lease_id: nil>,
 @details={},
 @messages={}>


From: /usr/local/bundle/gems/active-fedora-12.2.3/lib/active_fedora/validations.rb:70 ActiveFedora::Validations#valid?:
    67: def valid?(context = nil)
    68:   context ||= default_validation_context
    69:   output = super(context)
 => 70:   errors.empty? && output
    71: end

[27] pry(#<Text>)> output
=> false
[28] pry(#<Text>)> errors
=> #<ActiveModel::Errors:0x000055ce9d47e750
 @base=
  #<Text id: nil, head: [], tail: [], depositor: "admin@example.com", title: ["Kevon Looney"], date_uploaded: "2023-03-31 17:06:27", date_modified: "2023-03-31 17:06:27", state: nil, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksu
m: nil, owner: nil, is_child: nil, slug: "kevons", alternative_title: [], collection_information: [], contributor_role: ["publisher"], creator_role: [], date_digital: nil, digitization_specification: "digitization_specification", format:
"", location: [], media_type: ["Text"], mesh: [], ordering_information: nil, people_represented: [], resource_query: [], issue: "No. 2.", searchable_text: "Looney always holds us down!", table_of_contents: nil, volume: "Vol 2.", label: ni
l, relative_path: nil, import_url: nil, resource_type: ["Newspapers"], creator: [], contributor: ["Adam Silver"], description: ["Dub nation"], keyword: [], license: [], rights_statement: [], publisher: ["repository"], date_created: ["2/9/
2022"], subject: ["This is the subject"], language: [], identifier: ["Kevons"], based_near: [], related_url: [], bibliographic_citation: [], source: ["The source"], access_control_id: nil, representative_id: nil, thumbnail_id: nil, render
ing_ids: [], admin_set_id: "admin_set/default", embargo_id: nil, lease_id: nil>,
 @details={:identifier=>[{:error=>"must be unique"}, {:error=>"must be unique"}, {:error=>"must be unique"}]},
 @messages={:identifier=>["must be unique", "must be unique", "must be unique"]}>
```
</details>

**Comment by alishaevn** [comment]
further investigation has determined that [line 132](https://github.com/rails/rails/blob/v5.2.7.1/activesupport/lib/active_support/callbacks.rb#L132) of ActiveSupport::Callbacks#run_callbacks(v5.2.7.1) is where the error is being set. I'm unsure though what block was given and where. also, if a block was given, why did it yield false?

<details>
<summary>logs for ActiveSupport::Callbacks#run_callbacks</summary>

``` bash
From: /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:132 ActiveSupport::Callbacks#run_callbacks:

    127:         end
    128:
    129:         # Common case: no 'around' callbacks defined
    130:         if next_sequence.final?
    131:           next_sequence.invoke_before(env)
 => 132:           env.value = !env.halted && (!block_given? || yield)
    133:           next_sequence.invoke_after(env)
    134:           env.value
    135:         else
    136:           invoke_sequence.call
    137:         end

[12] pry(#<Text>)> self.errors
=> #<ActiveModel::Errors:0x0000564c5dfac6e8
 @base=
  #<Text id: nil, head: [], tail: [], depositor: "admin@example.com", title: ["Kevon Looney"], date_uploaded: "2023-04-03 20:30:26", date_modified: "2023-04-03 20:30:28", state: nil, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksum: nil, owner: nil, is_child: nil, slug: "kevons", alternative_title: [], collection_information: [], contributor_role: ["publisher"], creator_role: [], date_digital: nil, digitization_specification: "digitization_specification", format: "", location: [], media_type: ["Text"], mesh: [], ordering_information: nil, people_represented: [], resource_query: [], issue: "No. 2.", searchable_text: "Looney always holds us down!", table_of_contents: nil, volume: "Vol 2.", label: nil, relative_path: nil, import_url: nil, resource_type: ["Newspapers"], creator: [], contributor: ["Adam Silver"], description: ["Dub nation"], keyword: [], license: [], rights_statement: [], publisher: ["repository"], date_created: ["2/9/2022"], subject: ["This is the subject"], language: [], identifier: ["Kevons"], based_near: [], related_url: [], bibliographic_citation: [], source: ["The source"], access_control_id: nil, representative_id: nil, thumbnail_id: nil, rendering_ids: [], admin_set_id: "admin_set/default", embargo_id: nil, lease_id: nil>,
 @details={},
 @messages={}>

[13] pry(#<Text>)> next

From: /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/callbacks.rb:133 ActiveSupport::Callbacks#run_callbacks:

    128:
    129:         # Common case: no 'around' callbacks defined
    130:         if next_sequence.final?
    131:           next_sequence.invoke_before(env)
    132:           env.value = !env.halted && (!block_given? || yield)
 => 133:           next_sequence.invoke_after(env)
    134:           env.value
    135:         else
    136:           invoke_sequence.call
    137:         end
    138:       end

[13] pry(#<Text>)> self.errors
=> #<ActiveModel::Errors:0x0000564c5dfac6e8
 @base=
  #<Text id: nil, head: [], tail: [], depositor: "admin@example.com", title: ["Kevon Looney"], date_uploaded: "2023-04-03 20:30:26", date_modified: "2023-04-03 20:30:28", state: nil, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksum: nil, owner: nil, is_child: nil, slug: "kevons", alternative_title: [], collection_information: [], contributor_role: ["publisher"], creator_role: [], date_digital: nil, digitization_specification: "digitization_specification", format: "", location: [], media_type: ["Text"], mesh: [], ordering_information: nil, people_represented: [], resource_query: [], issue: "No. 2.", searchable_text: "Looney always holds us down!", table_of_contents: nil, volume: "Vol 2.", label: nil, relative_path: nil, import_url: nil, resource_type: ["Newspapers"], creator: [], contributor: ["Adam Silver"], description: ["Dub nation"], keyword: [], license: [], rights_statement: [], publisher: ["repository"], date_created: ["2/9/2022"], subject: ["This is the subject"], language: [], identifier: ["Kevons"], based_near: [], related_url: [], bibliographic_citation: [], source: ["The source"], access_control_id: nil, representative_id: nil, thumbnail_id: nil, rendering_ids: [], admin_set_id: "admin_set/default", embargo_id: nil, lease_id: nil>,
 @details={:identifier=>[{:error=>"must be unique"}]},
 @messages={:identifier=>["must be unique"]}>

[14] pry(#<Text>)> env.value
=> false

[15] pry(#<Text>)> env
=> #<struct ActiveSupport::Callbacks::Filters::Environment
 target=
  #<Text id: nil, head: [], tail: [], depositor: "admin@example.com", title: ["Kevon Looney"], date_uploaded: "2023-04-03 20:30:26", date_modified: "2023-04-03 20:30:28", state: nil, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksum: nil, owner: nil, is_child: nil, slug: "kevons", alternative_title: [], collection_information: [], contributor_role: ["publisher"], creator_role: [], date_digital: nil, digitization_specification: "digitization_specification", format: "", location: [], media_type: ["Text"], mesh: [], ordering_information: nil, people_represented: [], resource_query: [], issue: "No. 2.", searchable_text: "Looney always holds us down!", table_of_contents: nil, volume: "Vol 2.", label: nil, relative_path: nil, import_url: nil, resource_type: ["Newspapers"], creator: [], contributor: ["Adam Silver"], description: ["Dub nation"], keyword: [], license: [], rights_statement: [], publisher: ["repository"], date_created: ["2/9/2022"], subject: ["This is the subject"], language: [], identifier: ["Kevons"], based_near: [], related_url: [], bibliographic_citation: [], source: ["The source"], access_control_id: nil, representative_id: nil, thumbnail_id: nil, rendering_ids: [], admin_set_id: "admin_set/default", embargo_id: nil, lease_id: nil>,
 halted=false,
 value=false>

[16] pry(#<Text>)> block_given?
=> true

[17] pry(#<Text>)> yield
=> false
```
</details>

**Comment by alishaevn** [comment]
I looked at this ticket with jeremy and we found the problem. [CustomSlugs::SlugBehavior#check_slug](https://github.com/scientist-softserv/louisville-hyku/blob/main/app/models/custom_slugs/slug_behavior.rb#L32-L41) (in the lv codebase) was returning the error. that file is included in each of the model and collection classes. the method in question, is run as a validation for slugs.

we updated line 36 of the above method from `possible_duplicates.count.positive?` to `possible_duplicates.any? { |pd| pd.slug == slug }`. the result can be seen below.

<details>
<summary>checking for duplicates</summary>

``` bash
# this is defined in [CustomSlugs::SlugBehavior#set_slug](https://github.com/scientist-softserv/louisville-hyku/blob/main/app/models/custom_slugs/slug_behavior.rb#L43-L46)
irb(main):008:0> slug = 'singles'.truncate(75, omission: '').parameterize.underscore
=> "singles"

irb(main):009:0> possible_duplicates = ActiveFedora::Base.where(slug_tesim: slug)
=> [#<Text id: "3e05bbd2-af85-4286-9bc3-570183ce3875", head: [], tail: [], depositor: "admin@example.com", title: ["single"], date_uploaded: "2023-03-30 22:14:40", date_modified: "2023-03-30 22:14:40", state: #<ActiveTriples::Resourc...

irb(main):010:0> possible_duplicates.count.positive?
=> true

irb(main):011:0> possible_duplicates
=> [#<Text id: "3e05bbd2-af85-4286-9bc3-570183ce3875", head: [], tail: [], depositor: "admin@example.com", title: ["single"], date_uploaded: "2023-03-30 22:14:40", date_modified: "2023-03-30 22:14:40", state: #<ActiveTriples::Resource:0x6bf1c ID:<http://fedora.info/definitions/1/0/access/ObjState#active>>, proxy_depositor: nil, on_behalf_of: nil, arkivo_checksum: nil, owner: nil, is_child: nil, slug: "single", alternative_title: [], collection_information: [], contributor_role: [], creator_role: [], date_digital: nil, digitization_specification: nil, format: nil, location: [], media_type: [], mesh: [], ordering_information: nil, people_represented: [], resource_query: [], issue: nil, searchable_text: nil, table_of_contents: nil, volume: nil, label: nil, relative_path: nil, import_url: nil, resource_type: [], creator: [], contributor: [], description: [], keyword: [], license: [], rights_statement: [], publisher: [], date_created: [], subject: [], language: [], identifier: ["single"], based_near: [], related_url: [], bibliographic_citation: [], source: [], access_control_id: "1f472c1b-6603-46ec-8606-8e9a4e3a542b", representative_id: nil, thumbnail_id: nil, rendering_ids: [], admin_set_id: "admin_set/default", embargo_id: nil, lease_id: nil>]

irb(main):015:0> possible_duplicates.any? { |pd| pd.slug == slug }
=> false
```
</details>


next I tried to create works manually to see if the problem was resolved. it allowed me to create a work with an identifier and title of `beat` followed by a work with an identifier and title of `beats`. 🎉  however, while the works were created correctly, the `beats` title and identifier do not display correctly.

<details>
<summary>beat</summary>

``` bash
irb(main):019:0> Text.where(slug: 'beat').count
=> 2

irb(main):022:0> Text.find '3b5cd0c5-f55a-45e9-837f-3574f9f86a90'
=> #<Text id: "3b5cd0c5-f55a-45e9-837f-3574f9f86a90", title: ["beat"], slug: "beat", identifier: ["beat"], ...>
```

![Image](https://user-images.githubusercontent.com/29032869/229914042-ae7b7a7e-0334-4a84-8d3c-3110d623beab.png)
</details>

<details>
<summary>beats</summary>

``` bash
irb(main):020:0> Text.where(slug: 'beats').count
=> 2

irb(main):023:0> Text.find 'ab46bf3b-78cd-4db5-a08f-8d532149fac7'
=> #<Text id: "ab46bf3b-78cd-4db5-a08f-8d532149fac7, title: ["beats"], slug: "beats", identifier: ["beats"], ...>
```

![Image](https://user-images.githubusercontent.com/29032869/229913400-66971fd6-06de-4d73-be4b-b79215d603f1.png)
</details>

**Comment by alishaevn** [comment]
when looking at the presenter for the "beats" work, several solr properties are saved as "beat" instead.



![Image](https://user-images.githubusercontent.com/29032869/229929337-94607fb4-e453-4573-b96a-b372969602d6.png)

**Comment by alishaevn** [comment]
the solr document is actually right, seen below, so it's the presenter that's messing things up somehow.

<details>
<summary>solr doc</summary>

![Image](https://user-images.githubusercontent.com/29032869/230156950-375ebc67-448c-4881-a615-f7a6bd5aec22.png)
</details>

**Comment by alishaevn** [comment]
figured out the problem! ref: #182

**Comment by alishaevn** [comment]
reopening because I'm adding specs in a different pr.

**Comment by alishaevn** [comment]
@DiemBTran this is ready for staging qa! you can use"/app/samvera/hyrax-webapp/tmp/imports/originals/two_up/two_up.csv" as the server path.

**Comment by alishaevn** [comment]
diem is out sick today so I've kicked off [importer 2](https://louisville-hyku-staging.notch8.cloud/importers/11?locale=en) on staging.

**Comment by rachelihoward** [comment]
Please tell me it’s not on our hyku-docker-dev site! I have an import still in process there – I started it on March 30 and it’s not yet complete. I was wondering what was taking so long.

**Comment by rachelihoward** [comment]
Phew!  Thanks for clarifying…

**Comment by alishaevn** [comment]
the importer above failed because the [deploy to main](https://github.com/scientist-softserv/louisville-hyku/actions/runs/4632129477) with the necessary code changes failed on april 6.

**Comment by alishaevn** [comment]
[two_up.zip](https://github.com/scientist-softserv/louisville-hyku/files/11193625/two_up.zip)


after updating the volumes on staging and redeploying, I was able to successfully rerun the importer using the csv and files in the zip above. 🎉 


![Image](https://user-images.githubusercontent.com/29032869/230987944-7201bffc-7a4c-4d0b-b6ea-77c5c5969477.png)

**Comment by alishaevn** [comment]
@rkuehn-uofl @rachelihoward please take a look at https://github.com/rkuehn-uofl/hyku/pull/25 and qa!

**Comment by rkuehn-uofl** [comment]
@alishaevn we're testing the latest code. 
CC: @rachelihoward

**Comment by rachelihoward** [comment]
@alishaevn we successfully tested this on our dev server (which was pretty much empty)! The soon-to-be-production server, with 81K plus items on it, has become so buggy that we can't successfully test anything on it.
