### ISSUE TITLE
When creating JPEGs from PDFs one or more pages is skipped

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/louisville-hyku#176]
# Summary

Sometimes when JPEGs are generated from a PDF, one or more pages are skipped

# Acceptance Criteria

- [x] All pages of a PDF are created when uploading and processing the image.  

# Testing Instructions
upload a handful of PDFs with multiple pages and make sure all of the items show.  

# Notes
Violet has been working on silent failures in bulkrax and job processing.  It may be worth talking to Jeremy on things found in other projects.

**Comment by rachelihoward** [comment]
Bug fixes took care of this issue.
