### ISSUE TITLE
Ldp::NotFound (staging)

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#34]
Importing via bulkrax creates the following errors on staging: https://lv-hyku-staging.notch8.cloud/sidekiq/retries

This occurred after staging crashed and I reset the db

![Image](https://user-images.githubusercontent.com/29311858/202281400-d565b9e7-cb8c-4622-9f87-02a59c30eee3.png)

**Comment by DiemBTran** [comment]
Shana - Sept 2022

---

sample file uploads successfully locally but still causes Ldp::NotGone errors in staging- note this is a csv that has been previously uploaded, perhaps we need to try a branch new csv



[warriors_3_children.csv](https://github.com/scientist-softserv/louisville-hyku/files/10025291/warriors_3_children.csv)

**Comment by DiemBTran** [comment]
Shana - Sept 2022

---

to confirm also, manually creating works w file sets produces the same error.
manually creating works a no file set is fine.

**Comment by DiemBTran** [comment]
Shana Sept 2022

---



![Image](https://user-images.githubusercontent.com/29311858/202282531-8507d8fc-c68e-440d-b043-d94dea391195.png)

**Comment by DiemBTran** [comment]
Alisha - Oct 2022

---

there's a lot of conversation about this in slack too. I tried running through some reset commands on friday and in the end was able to create manual works with or without files. importing a previously imported csv did not work however. (I think the overall problem with this is uploading/importing file sets that existed before the db was wiped)

more details, with a stack trace and everything can be found [in the slack thread](https://assaydepot.slack.com/archives/G0313NK5NMA/p1664467995541009?thread_ts=1664387275.241309&cid=G0313NK5NMA).

**Comment by DiemBTran** [comment]
Shana - Oct 2022

---

we've seen this before https://gitlab.com/notch8/louisville-hyku/-/issues/10
